//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int DOB { get; set; }
        public int License { get; set; }
        public string CandidateName { get; set; }
        public Nullable<int> Candidate_CandidateId { get; set; }
        public string Email { get; set; }
        public byte[] User_Image { get; set; }
        public string User_Password { get; set; }
        public Nullable<bool> Voting_Status { get; set; }
    }
}
